hu_story_location: '{project-root}/.cochas/artifacts/HU'
hu_refinamiento_location: '{project-root}/.cochas/artifacts/HU/refinamientos'
artifacts_location: '{project-root}/.cochas/artifacts'
adr_location: '{project-root}/.cochas/artifacts/ADR'
analisis_location: '{project-root}/.cochas/artifacts/analisis'
backlog_location: '{project-root}/.cochas/artifacts/backlog_desarrollo.md'
contexto_proyecto_location: '{project-root}/.cochas/artifacts/contexto_proyecto.md'
reglas_arquitectonicas_location: '{project-root}/.cochas/artifacts/reglas_arquitectonicas.md'
plan_desarrollo_location: '{project-root}/.cochas/artifacts/planes_de_desarrollo'
ejecuciones_location: '{project-root}/.cochas/artifacts/ejecuciones'
code_smells_reports_location: '{project-root}/.cochas/artifacts/code_smells'

# Session
session_location: '{project-root}/.cochas/session'
session_state_location: '{project-root}/.cochas/session/session_state.json'

# Plantillas
plantillas_location: '{project-root}/.cochas/plantillas'
contexto_proyecto_plantilla: '{project-root}/.cochas/plantillas/contexto_proyecto_plantilla.md'
backlog_desarrollo_plantilla: '{project-root}/.cochas/plantillas/backlog_desarrollo_plantilla.md'

ruta_herramientas: '{project-root}/.cochas/herramientas/herramientas-activas.md'

architecture_sharded_location: '{project-root}/.cochas/artifacts/architecture'
architecture_file: '{project-root}/.cochas/artifacts/architecture/index.md'

communication_language: Español
document_output_language: Español
user_name: Javier Garcia
output_folder: '{project-root}/.cochas'

orchestrator_name: Cochas 
orchestrator_version: 3.1
